HASRental/ViewModels/KreirajUlogu.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HASRental.ViewModels
{
    public class KreirajUlogu
    {
        [Required]
        [Display(Name="Naziv uloge")]
        public string NazivUloge { get; set; }

    }

  
}

HASRental/Controllers/LokacijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HASRental.Models;
using Microsoft.AspNetCore.Authorization;

namespace HASRental.Controllers
{
    public class LokacijaController : Controller
    {
        private readonly NasContext _context;

        public LokacijaController(NasContext context)
        {
            _context = context;
        }

        // GET: Lokacija
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Lokacija.ToListAsync());
        }
        [Authorize(Roles = "Admin")]

        // GET: Lokacija/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lokacija = await _context.Lokacija
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lokacija == null)
            {
                return NotFound();
            }

            return View(lokacija);
        }

        [Authorize(Roles = "Admin")]
        // GET: Lokacija/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lokacija/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Adresa,Grad,Kanton,Drazava,PostanskiBroj")] Lokacija lokacija)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lokacija);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lokacija);
        }

        // GET: Lokacija/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lokacija = await _context.Lokacija.FindAsync(id);
            if (lokacija == null)
            {
                return NotFound();
            }
            return View(lokacija);
        }

        // POST: Lokacija/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Adresa,Grad,Kanton,Drazava,PostanskiBroj")] Lokacija lokacija)
        {
            if (id != lokacija.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lokacija);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LokacijaExists(lokacija.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lokacija);
        }

        // GET: Lokacija/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lokacija = await _context.Lokacija
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lokacija == null)
            {
                return NotFound();
            }

            return View(lokacija);
        }

        // POST: Lokacija/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lokacija = await _context.Lokacija.FindAsync(id);
            _context.Lokacija.Remove(lokacija);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        private bool LokacijaExists(int id)
        {
            return _context.Lokacija.Any(e => e.Id == id);
        }
    }
}

HASRental/Controllers/VoziloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HASRental.Models;
using Microsoft.AspNetCore.Authorization;

namespace HASRental.Controllers
{
    public class VoziloController : Controller
    {
        private readonly NasContext _context;

        public VoziloController(NasContext context)
        {
            _context = context;
        }

        // GET: Vozilo
        public async Task<IActionResult> Index()
        {
            var nasContext = _context.Vozilo.Include(v => v.Proizvodjac).Include(v => v.TrenutnaLokacija).Include(v => v.VoziloKategorija);
            return View(await nasContext.ToListAsync());
        }

        // GET: Vozilo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vozilo = await _context.Vozilo
                .Include(v => v.Proizvodjac)
                .Include(v => v.TrenutnaLokacija)
                .Include(v => v.VoziloKategorija)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vozilo == null)
            {
                return NotFound();
            }

            return View(vozilo);
        }

        // GET: Vozilo/Create
        public IActionResult Create()
        {
            ViewData["ProizvodjacId"] = new SelectList(_context.Proizvodjac, "Id", "Naziv");
            ViewData["TrenutnaLokacijaId"] = new SelectList(_context.Lokacija, "Id", "Grad");
            ViewData["VoziloKategorijaId"] = new SelectList(_context.VoziloKategorija, "Id", "Ime");
            return View();
        }

        // POST: Vozilo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Create([Bind("Id,VoziloKategorijaId,ProizvodjacId,TrenutnaLokacijaId,Model,GodinaProizvodnje,Kilometraza,Boja")] Vozilo vozilo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vozilo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProizvodjacId"] = new SelectList(_context.Proizvodjac, "Id", "Naziv", vozilo.ProizvodjacId);
            ViewData["TrenutnaLokacijaId"] = new SelectList(_context.Lokacija, "Id", "Grad", vozilo.TrenutnaLokacijaId);
            ViewData["VoziloKategorijaId"] = new SelectList(_context.VoziloKategorija, "Id", "Ime", vozilo.VoziloKategorijaId);
            return View(vozilo);
        }

        // GET: Vozilo/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vozilo = await _context.Vozilo.FindAsync(id);
            if (vozilo == null)
            {
                return NotFound();
            }
            ViewData["ProizvodjacId"] = new SelectList(_context.Proizvodjac, "Id", "Id", vozilo.ProizvodjacId);
            ViewData["TrenutnaLokacijaId"] = new SelectList(_context.Lokacija, "Id", "Id", vozilo.TrenutnaLokacijaId);
            ViewData["VoziloKategorijaId"] = new SelectList(_context.VoziloKategorija, "Id", "Id", vozilo.VoziloKategorijaId);
            return View(vozilo);
        }

        // POST: Vozilo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,VoziloKategorijaId,ProizvodjacId,TrenutnaLokacijaId,Model,GodinaProizvodnje,Kilometraza,Boja")] Vozilo vozilo)
        {
            if (id != vozilo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vozilo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VoziloExists(vozilo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProizvodjacId"] = new SelectList(_context.Proizvodjac, "Id", "Id", vozilo.ProizvodjacId);
            ViewData["TrenutnaLokacijaId"] = new SelectList(_context.Lokacija, "Id", "Id", vozilo.TrenutnaLokacijaId);
            ViewData["VoziloKategorijaId"] = new SelectList(_context.VoziloKategorija, "Id", "Id", vozilo.VoziloKategorijaId);
            return View(vozilo);
        }

        // GET: Vozilo/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vozilo = await _context.Vozilo
                .Include(v => v.Proizvodjac)
                .Include(v => v.TrenutnaLokacija)
                .Include(v => v.VoziloKategorija)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vozilo == null)
            {
                return NotFound();
            }

            return View(vozilo);
        }

        // POST: Vozilo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vozilo = await _context.Vozilo.FindAsync(id);
            _context.Vozilo.Remove(vozilo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        private bool VoziloExists(int id)
        {
            return _context.Vozilo.Any(e => e.Id == id);
        }
    }
}

HASRental/Views/Admin/AdminPanel.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Korisnik> SignInManager
@inject UserManager<Korisnik> UserManager
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--=== Favicon ===-->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <!--=== Bootstrap CSS ===-->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <!--=== Slicknav CSS ===-->
    <link href="~/css/plugins/slicknav.min.css" rel="stylesheet">
    <!--=== Magnific Popup CSS ===-->
    <link href="~/css/plugins/magnific-popup.css" rel="stylesheet">
    <!--=== Owl Carousel CSS ===-->
    <link href="~/css/plugins/owl.carousel.min.css" rel="stylesheet">
    <!--=== Gijgo CSS ===-->
    <link href="~/css/plugins/gijgo.css" rel="stylesheet">
    <!--=== FontAwesome CSS ===-->
    <link href="~/css/font-awesome.css" rel="stylesheet">
    <!--=== Theme Reset CSS ===-->
    <link href="~/css/reset.css" rel="stylesheet">
    <!--=== Main Style CSS ===-->
    <link href="~/css/style.css" rel="stylesheet">
    <!--=== Responsive CSS ===-->
    <link href="~/css/responsive.css" rel="stylesheet">
</head>
<section id="page-title-area" class="section-padding overlay">
    <div class="container">
        <div class="row">
            <!-- Page Title Start -->
            <div class="col-lg-12">
                <div class="section-title  text-center">
                    <h2>ADMIN PANEL</h2>
                    <span class="title-line"><i class="fa fa-car"></i></span>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
            </div>
            <!-- Page Title End -->
        </div>
    </div>
</section>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 2%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>
<table>
    <tr>
        <th>Korisnici</th>
        <th>Vozila</th>
        <th>Proizvodjaci</th>
        <th>Lokacija</th>
    </tr>
    <tr>
        <td>
            <form>
                <button asp-controller="Admin" asp-action="Index">Prikaz svih registrovanih</button>
            </form>
        </td>
        <td>
            <form>
                <button asp-controller="Vozilo" asp-action="Index">Prikaz svih vozila</button>
            </form>
        </td>
        <td>
            <form>
                <button asp-controller="Proizvodjac" asp-action="Index">Prikaz svih proizvođača</button>
            </form>
        </td>
        <td>
            <form>
                <button asp-controller="Lokacija" asp-action="Index">Prikaz svih lokacija</button>
            </form>
        </td>
    </tr>
    <tr>
        <td>
            <form>
                <button class="col-lg-8 d-none d-xl-block" asp-area="Identity" asp-page="/Account/Register">Registracija korisnika</button>
            </form>
        </td>
        <td>
            <form>
                <button asp-controller="Vozilo" asp-action="Create">Dodaj novo vozilo</button>
            </form>
        </td>
        <td>
            <form>
                <button asp-controller="Proizvodjac" asp-action="Create">Dodaj novog proizvođača</button>
            </form>
        </td>
        <td>
            <form>
                <button asp-controller="Lokacija" asp-action="Create">Dodaj novu lokaciju</button>
            </form>
        </td>
    </tr>
    <tr>
        <td>
            <form>
                <button asp-controller="Admin" asp-action="KreirajUlogu">Dodaj novu ulogu</button>
            </form>
        </td>
        <td>
            <form>
                <button asp-controller="VoziloKategorija" asp-action="Index">Prikaz svih kategorija vozila</button>
            </form>
        </td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>
            <form>
                <button asp-controller="VoziloKategorija" asp-action="Create">Dodaj novu kategoriju vozila</button>
            </form>
        </td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>
            <form>
                <button asp-controller="TipRezervoara" asp-action="Index">Prikaz svih tipova rezervoara</button>
            </form>
        </td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td><form>
    <button asp-controller="TipRezervoara" asp-action="Create">Dodaj novi tip rezervoara</button>
</form></td>
        <td></td>
        <td></td>
    </tr>
</table>

HASRental/Views/Admin/Details.cshtml
@model IEnumerable<HASRental.Models.Renta>


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--=== Favicon ===-->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <!--=== Bootstrap CSS ===-->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <!--=== Slicknav CSS ===-->
    <link href="~/css/plugins/slicknav.min.css" rel="stylesheet">
    <!--=== Magnific Popup CSS ===-->
    <link href="~/css/plugins/magnific-popup.css" rel="stylesheet">
    <!--=== Owl Carousel CSS ===-->
    <link href="~/css/plugins/owl.carousel.min.css" rel="stylesheet">
    <!--=== Gijgo CSS ===-->
    <link href="~/css/plugins/gijgo.css" rel="stylesheet">
    <!--=== FontAwesome CSS ===-->
    <link href="~/css/font-awesome.css" rel="stylesheet">
    <!--=== Theme Reset CSS ===-->
    <link href="~/css/reset.css" rel="stylesheet">
    <!--=== Main Style CSS ===-->
    <link href="~/css/style.css" rel="stylesheet">
    <!--=== Responsive CSS ===-->
    <link href="~/css/responsive.css" rel="stylesheet">
</head>

<section id="page-title-area" class="section-padding overlay">
    <div class="container">
        <div class="row">
            <!-- Page Title Start -->
            <div class="col-lg-12">
                <div class="section-title  text-center">
                    <h2>Prikaz svih renti korisnika</h2>
                    <span class="title-line"><i class="fa fa-car"></i></span>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
            </div>
            <!-- Page Title End -->
        </div>
    </div>
</section>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 2%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>
<table class="table table-bordered">
    <thead style="text-align:center">
        <tr>
            <th style="white-space:nowrap">
                @Html.DisplayNameFor(model => model.DatumRentanja)
            </th>
            <th style="white-space:nowrap">
                @Html.DisplayNameFor(model => model.DatumVracanja)
            </th>
            <th style="white-space:nowrap">
                @Html.DisplayNameFor(model => model.DodatneNaznake)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Korisnik)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vozilo)
            </th>
            <th style="white-space:nowrap">
                @Html.DisplayNameFor(model => model.PocetnaLokacija)
            </th>
            <th style="white-space:nowrap">
                @Html.DisplayNameFor(model => model.KrajnjaLokacija)
            </th>
            <th style="white-space:nowrap">
                @Html.DisplayNameFor(model => model.TipRezervoara)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DatumRentanja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumVracanja)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.DodatneNaznake)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Korisnik.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vozilo.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PocetnaLokacija.Grad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KrajnjaLokacija.Grad)
            </td>
            <td width="50px">
                @Html.DisplayFor(modelItem => item.TipRezervoara.Opis)
            </td>
            <td width="75%">
                <a asp-controller="FakturaRente" asp-action="Details" asp-route-id="@item.Id">Prikaži fakturu</a> |
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    <a href='javascript:history.go(-1)'>Vrati se nazad</a>
</div>

HASRental/Views/Admin/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<HASRental.Models.Korisnik>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--=== Favicon ===-->
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
        <!--=== Bootstrap CSS ===-->
        <link href="~/css/bootstrap.min.css" rel="stylesheet">
        <!--=== Slicknav CSS ===-->
        <link href="~/css/plugins/slicknav.min.css" rel="stylesheet">
        <!--=== Magnific Popup CSS ===-->
        <link href="~/css/plugins/magnific-popup.css" rel="stylesheet">
        <!--=== Owl Carousel CSS ===-->
        <link href="~/css/plugins/owl.carousel.min.css" rel="stylesheet">
        <!--=== Gijgo CSS ===-->
        <link href="~/css/plugins/gijgo.css" rel="stylesheet">
        <!--=== FontAwesome CSS ===-->
        <link href="~/css/font-awesome.css" rel="stylesheet">
        <!--=== Theme Reset CSS ===-->
        <link href="~/css/reset.css" rel="stylesheet">
        <!--=== Main Style CSS ===-->
        <link href="~/css/style.css" rel="stylesheet">
        <!--=== Responsive CSS ===-->
        <link href="~/css/responsive.css" rel="stylesheet">
    </head>

    <section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Prikaz svih registrovanih</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
            margin-top: 2%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>

    <table class="table">
        <thead>
            <tr>
                @{

                }
                <th>
                    @Html.DisplayNameFor(model => model.Ime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Prezime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DatumRodenja)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BrojVozacke)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DatumIzdavanjaVozacke)
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prezime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumRodenja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BrojVozacke)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumIzdavanjaVozacke)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Detalji</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
    <div>
        <a href='javascript:history.go(-1)'>Vrati se nazad</a>
    </div>

HASRental/Views/Admin/KreirajUlogu.cshtml
@model HASRental.ViewModels.KreirajUlogu

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--=== Favicon ===-->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <!--=== Bootstrap CSS ===-->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <!--=== Slicknav CSS ===-->
    <link href="~/css/plugins/slicknav.min.css" rel="stylesheet">
    <!--=== Magnific Popup CSS ===-->
    <link href="~/css/plugins/magnific-popup.css" rel="stylesheet">
    <!--=== Owl Carousel CSS ===-->
    <link href="~/css/plugins/owl.carousel.min.css" rel="stylesheet">
    <!--=== Gijgo CSS ===-->
    <link href="~/css/plugins/gijgo.css" rel="stylesheet">
    <!--=== FontAwesome CSS ===-->
    <link href="~/css/font-awesome.css" rel="stylesheet">
    <!--=== Theme Reset CSS ===-->
    <link href="~/css/reset.css" rel="stylesheet">
    <!--=== Main Style CSS ===-->
    <link href="~/css/style.css" rel="stylesheet">
    <!--=== Responsive CSS ===-->
    <link href="~/css/responsive.css" rel="stylesheet">
</head>

<section id="page-title-area" class="section-padding overlay">
    <div class="container">
        <div class="row">
            <!-- Page Title Start -->
            <div class="col-lg-12">
                <div class="section-title  text-center">
                    <h2>Kreiraj novu ulogu</h2>
                    <span class="title-line"><i class="fa fa-car"></i></span>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
            </div>
            <!-- Page Title End -->
        </div>
    </div>
</section>
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger">
            </div>
            <div class="form-group">
                <label asp-for="NazivUloge"></label>
                <input asp-for="NazivUloge" class="form-control" />
                <span asp-validation-for="NazivUloge" class="text-danger"></span>

            </div>
            <button type="submit" class="btn btn-primary" style="width:auto">Kreiraj ulogu</button>
        </form>

    </div>

</div>
<div>
    <a href='javascript:history.go(-1)'>Vrati se nazad</a>
</div>